name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install pnpm 
        run: npm i -g pnpm

      - name: Install dependencies 🔧
        run: pnpm install --frozen-lockfile

      - name: Lint 🖊
        run: pnpm run check-lint

      - name: Build client ✅
        run: pnpm run build

      - name: Test server 🖥
        run: pnpm run test
