name: CI
on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install pnpm 
        run: npm i -g pnpm

      - name: Install dependencies 🔧
        run: pnpm install

      - name: Lint 🖊
        run: pnpm run check-lint

      - name: Set environment variables 🔏
        run: |
          touch .env
          echo NEXT_PUBLIC_CLERK_FRONTEND_API=clerk.8bqex.mkl5j.lcl.dev >> .env

      - name: Build ✅
        run: pnpx prisma generate && pnpm run build
